import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:sanaa_artl/models/exhibition/exhibition.dart';
import '../../../providers/theme_provider.dart';
import '../../../themes/app_colors.dart';
import 'exhibition_card.dart';

class FeaturedExhibitions extends StatelessWidget {
  const FeaturedExhibitions({super.key});

  @override
  Widget build(BuildContext context) {
    final isDark = Provider.of<ThemeProvider>(context).isDarkMode;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: Text(
            'أبرز المعارض الجديدة',
            style: TextStyle(
              fontSize: 22,
              fontWeight: FontWeight.bold,
              fontFamily: 'Tajawal',
              color: AppColors.getPrimaryColor(isDark),
            ),
          ),
        ),
        const SizedBox(height: 16),
        SizedBox(
          height: 450,
          child: ListView(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.symmetric(horizontal: 16),
            children: [
              ExhibitionCard(
                title: 'معرض التراث اليمني',
                description: 'أجمل اللوحات المستوحاة من التراث اليمني الأصيل',
                imageUrl: "assets/images/image1.jpg",
                exhibition: Exhibition(
                  id: '2',
                  title: 'title',
                  curator: 'curator',
                  type: ExhibitionType.open,
                  status: 'status',
                  description: 'description',
                  date: 'date',
                  location: 'location',
                  artworksCount: 11,
                  visitorsCount: 122,
                  startDate: DateTime(22),
                  endDate: DateTime(12),
                  imageUrl: "assets/images/image1.jpg",
                  isActive: true,
                ),
                animationDelay: const Duration(),
                onTap: () {},
              ),
              const SizedBox(width: 16),
              ExhibitionCard(
                title: 'فنون معاصرة',
                description: 'أعمال فنية معاصرة تجمع بين الأصالة والحداثة',
                imageUrl: "assets/images/image2.jpg",
                exhibition: Exhibition(
                  id: '2',
                  title: 'title',
                  curator: 'curator',
                  type: ExhibitionType.open,
                  status: 'status',
                  description: 'description',
                  date: 'date',
                  location: 'location',
                  artworksCount: 11,
                  visitorsCount: 122,
                  startDate: DateTime(22),
                  endDate: DateTime(12),
                  imageUrl: '',
                  isActive: true,
                ),
                animationDelay: const Duration(),
                onTap: () {},
              ),
              const SizedBox(width: 16),
              ExhibitionCard(
                title: 'مناظر طبيعية',
                description: 'استكشف جمال الطبيعة اليمنية عبر ريشة الفنانين',
                imageUrl: "assets/images/image3.jpg",
                exhibition: Exhibition(
                  id: '2',
                  title: 'title',
                  curator: 'curator',
                  type: ExhibitionType.open,
                  status: 'status',
                  description: 'description',
                  date: 'date',
                  location: 'location',
                  artworksCount: 11,
                  visitorsCount: 122,
                  startDate: DateTime(22),
                  endDate: DateTime(12),
                  imageUrl: '',
                  isActive: true,
                ),
                animationDelay: const Duration(),
                onTap: () {},
              ),
              const SizedBox(width: 16),
              ExhibitionCard(
                title: 'بورتريهات',
                description: 'صور شخصية تعبر عن هوية المجتمع اليمني',
                imageUrl: "assets/images/image4.jpg",
                exhibition: Exhibition(
                  id: '2',
                  title: 'title',
                  curator: 'curator',
                  type: ExhibitionType.open,
                  status: 'status',
                  description: 'description',
                  date: 'date',
                  location: 'location',
                  artworksCount: 11,
                  visitorsCount: 122,
                  startDate: DateTime(22),
                  endDate: DateTime(12),
                  imageUrl: "assets/images/image5.jpg",
                  isActive: true,
                ),
                animationDelay: const Duration(),
                onTap: () {},
              ),
            ],
          ),
        ),
        const SizedBox(height: 50),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 16),
          child: Text(
            'أبرز الدورات ',
            style: TextStyle(
              fontSize: 22,
              fontWeight: FontWeight.bold,
              fontFamily: 'Tajawal',
              color: AppColors.getPrimaryColor(isDark),
            ),
          ),
        ),
        const SizedBox(height: 16),
        SizedBox(
          height: 450,
          child: ListView(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.symmetric(horizontal: 16),
            children: [
              ExhibitionCard(
                title: 'معرض التراث اليمني',
                description: 'أجمل اللوحات المستوحاة من التراث اليمني الأصيل',
                imageUrl: "assets/images/image5.jpg",
                exhibition: Exhibition(
                  id: '2',
                  title: 'title',
                  curator: 'curator',
                  type: ExhibitionType.open,
                  status: 'status',
                  description: 'description',
                  date: 'date',
                  location: 'location',
                  artworksCount: 11,
                  visitorsCount: 122,
                  startDate: DateTime(22),
                  endDate: DateTime(12),
                  imageUrl: '',
                  isActive: true,
                ),
                animationDelay: const Duration(),
                onTap: () {},
              ),
              const SizedBox(width: 16),
              ExhibitionCard(
                title: 'فنون معاصرة',
                description: 'أعمال فنية معاصرة تجمع بين الأصالة والحداثة',
                imageUrl: "assets/images/image6.jpg",
                exhibition: Exhibition(
                  id: '2',
                  title: 'title',
                  curator: 'curator',
                  type: ExhibitionType.open,
                  status: 'status',
                  description: 'description',
                  date: 'date',
                  location: 'location',
                  artworksCount: 11,
                  visitorsCount: 122,
                  startDate: DateTime(22),
                  endDate: DateTime(12),
                  imageUrl: '',
                  isActive: true,
                ),
                animationDelay: const Duration(),
                onTap: () {},
              ),
              const SizedBox(width: 16),
              ExhibitionCard(
                title: 'مناظر طبيعية',
                description: 'استكشف جمال الطبيعة اليمنية عبر ريشة الفنانين',
                imageUrl: "assets/images/image1.jpg",
                exhibition: Exhibition(
                  id: '2',
                  title: 'title',
                  curator: 'curator',
                  type: ExhibitionType.open,
                  status: 'status',
                  description: 'description',
                  date: 'date',
                  location: 'location',
                  artworksCount: 11,
                  visitorsCount: 122,
                  startDate: DateTime(22),
                  endDate: DateTime(12),
                  imageUrl: '',
                  isActive: true,
                ),
                animationDelay: const Duration(),
                onTap: () {},
              ),
              const SizedBox(width: 16),
              ExhibitionCard(
                title: 'بورتريهات',
                description: 'صور شخصية تعبر عن هوية المجتمع اليمني',
                imageUrl: "assets/images/image5.jpg",
                exhibition: Exhibition(
                  id: '2',
                  title: 'title',
                  curator: 'curator',
                  type: ExhibitionType.open,
                  status: 'status',
                  description: 'description',
                  date: 'date',
                  location: 'location',
                  artworksCount: 11,
                  visitorsCount: 122,
                  startDate: DateTime(22),
                  endDate: DateTime(12),
                  imageUrl: "assets/images/image5.jpg",
                  isActive: true,
                ),
                animationDelay: const Duration(),
                onTap: () {},
              ),
            ],
          ),
        ),
      ],
    );
  }
}
